version: '3.3'

services:
   db:
     image: agileops/fastds-tutorial:latest
     # build: .
     volumes:
       - ./data:/work-dir/data
     restart: "no"
     ports:
       - 8888:8888
       - 8088:8088
       - 9000:9000
     environment:
       BIND_ADDRESS: 0.0.0.0
     command:
       bootstrap.sh
